Repository openvinotoolkit/model_analyzer, pull requests merged in 2021-12, with the labels that each got.

#40 [CI] [skip-name] Transition to the new package (#355, ww48.1`22)
  automation/Dockerfile
Labels: enhancement

#41 [70534] Safely get shapes for dynamic models
  model_analyzer/network_metadata.py
Labels: bug

#42 [72889] Transition to the new package (#388, ww50.2) with tools distributed through wheels
  automation/Dockerfile
Labels: blocked

#44 [71552] Cast Dimension to int
  model_analyzer/network_metadata.py
Labels: bug
