Repository openvinotoolkit/model_analyzer, pull requests merged in 2022-03, with the labels that each got.

#90 [80607] Transition to the new package (#612, ww10.1'22)
  automation/Dockerfile
Labels: enhancement

#92 [80772] Transition to the new package (#618, ww10.3`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#94 [81138] Transition to the new package (#620, ww10.4'22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#97 [81490] Transition to the new package (#638, ww12.2'22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#100 [82021] Transition to the new pacakge (#643, ww12.5)
  automation/Dockerfile
Labels: enhancement

#101 [81002] Update master with latest changes from 2022.1
  automation/Dockerfile
Labels: to-be-merged
