Repository openvinotoolkit/model_analyzer, pull requests merged in 2022-01, with the labels that each got.

#47 [CI] [skip-name] Transition to the new package (#496, ww03.1`22)
  automation/Dockerfile
Labels: to-be-merged

#48 [CI] [skip-name] Transition to the new package (#511, ww03.5`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#43 [72889] Update methods to get shape
  model_analyzer/network_metadata.py
Labels: to-be-merged

#46 [71551] OpenVINO 2.0
  automation/Dockerfile
  automation/package_BOM.txt
  bom_test.py
  model_analyzer/__main__.py
  model_analyzer/constants.py
  model_analyzer/layer_provider.py
  model_analyzer/layout_utils.py
  model_analyzer/model_complexity.py
  model_analyzer/model_metadata.py
  model_analyzer/network_metadata.py
  model_analyzer/openvino_core_service.py
  model_analyzer/shape_utils.py
  model_analyzer/uncounted_layers.py
  tests/IRv10_models_test.py
  tests/data/IRv10_models.json
  tests/data/onnx_models.json
  tests/generic_e2e_test_case.py
  tests/model_metadata_test.py
  tests/onnx_models_test.py
Labels: enhancement

#49 [76734] Transition to the new package (#528, ww04.3`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#51 [76861] Transition to the new package (#541, ww04.5`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#52 [77149] Transition to the new package (#550, ww05.2`22)
  automation/Dockerfile
Labels: enhancement

#54 [77263] Transition to the new package (#553, ww05.3`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged
