Repository openvinotoolkit/model_analyzer, pull requests merged in 2022-02, with the labels that each got.

#57 [77537] Transition to the new package (#558, ww06.1`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#59 [77692] Transition to the new package (#561, ww06.2`22)
  automation/Dockerfile
Labels: enhancement

#58 [77419] Add synonyms with underscores for command line arguments
  model_analyzer/__main__.py
Labels: enhancement

#61 [77859] Restore layer data collection
  model_analyzer/model_complexity.py
Labels: bug

#53 [70156] Get filter shapes for DeformableConvolution from the third input
  model_analyzer/layer_provider.py
  model_analyzer/shape_utils.py
Labels: bug

#63 [78069] Transition to the new package (#571, ww06.4`22)
  automation/Dockerfile
Labels: enhancement

#62 [77995] Fix for License-Identifier
  .pylintrc
  bom_test.py
  model_analyzer.py
  model_analyzer/__init__.py
  model_analyzer/__main__.py
  model_analyzer/constants.py
  model_analyzer/layer_provider.py
  model_analyzer/layout_utils.py
  model_analyzer/model_complexity.py
  model_analyzer/model_metadata.py
  model_analyzer/openvino_core_service.py
  model_analyzer/shape_utils.py
  model_analyzer/uncounted_layers.py
  model_analyzer/value_converter.py
  tests/IRv10_models_test.py
  tests/__init__.py
  tests/constants.py
  tests/download_models.py
  tests/generic_e2e_test_case.py
  tests/model_metadata_test.py
  tests/ngraph_test.py
  tests/onnx_models_test.py
  tests/utils.py
Labels: documentation, to-be-merged

#64 [78162] Get layout safely
  model_analyzer/layer_provider.py
  model_analyzer/layout_utils.py
  model_analyzer/model_metadata.py
  model_analyzer/shape_utils.py
Labels: bug, to-be-merged

#60 [77421] Wording corrections
  DEVELOPER.md
  README.md
  model_analyzer/__main__.py
  model_analyzer/model_complexity.py
Labels: documentation

#65 [78523] Transition to the new package (#573, ww07.1`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#69 [75489] Super-resolution int8 failed
  model_analyzer/model_metadata.py
Labels: bug, to-be-merged

#71 [78784] Transition to the new package (#579, ww07.4`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#76 [skip-name] Transition to the new package (#583, ww08.2 22)
  automation/Dockerfile
Labels: enhancement

#77 [79617] Transition to the new package (#593, ww08.3`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#81 [79985] Transition to the new package (#602, ww09.1`22)
  automation/Dockerfile
Labels: enhancement, to-be-merged

#87 [80325] Transition to the new package (#606, ww09.3'22)
  automation/Dockerfile
Labels: enhancement

#89 [80476] Transition to the new package (#610, ww09.5'22)
  automation/Dockerfile
Labels: enhancement
